//公共
export const COM_NAV_STATUS     = 'COM_NAV_STATUS'
export const COM_HEADER_STATUS  = 'COM_HEADER_STATUS'
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'

export const COM_SHOW_TOAST = 'COM_SHOW_TOAST'              //显示toast
export const COM_SHOW_SUCCESS = 'COM_SHOW_SUCCESS'          //显示成功toast
export const COM_SHOW_FAIL = 'COM_SHOW_FAIL'                //显示失败toast
export const COM_TOAST_MSG = 'COM_TOAST_MSG'                //显示toast文字
export const COM_SHOW_ALERT = 'COM_SHOW_ALERT'
export const COM_ALERT_MSG = 'COM_ALERT_MSG'
export const COM_SELECT_TIMER = 'COM_SELECT_TIMER'
export const COM_SHOW_TIME_PICKER = 'COM_SHOW_TIME_PICKER'  //显示timepicker
export const COM_IN_BROWER ='COM_IN_BROWER' //是否在浏览器中
export const COM_PAGE_TITLE='COM_PAGE_TITLE'
export const COM_SHOW_TITLE='COM_SHOW_TITLE'

//user 用户
export const COM_SELECT_TOKEN	= 'COM_SELECT_TOKEN'
export const SET_REFRESH	= 'SET_REFRESH'

//其他
export const GET_CRYPTOJS_AES_KEY	= 'GET_CRYPTOJS_AES_KEY'
export const COM_GET_BACK_INFO = 'COM_GET_BACK_INFO'
export const COM_UPDATE_APP_SETTING = 'COM_UPDATE_APP_SETTING'

export const SET_LIST_CARD = 'SET_LIST_CARD'

export const SET_ROUTER_SCROLL = 'SET_ROUTER_SCROLL'

//海报
export const GET_POSTER_DAYLIMIT	= 'GET_POSTER_DAYLIMIT'
export const GET_BUSIN_LIST	= 'GET_BUSIN_LIST'
export const GET_BUSIN_DOM_DATA	= 'GET_BUSIN_DOM_DATA'

export const SET_BUSIN_DATA	= 'SET_BUSIN_DATA'
export const SET_USER_POSTERS	= 'SET_USER_POSTERS'


export const SET_PLAT_FORM_LIST = 'GET_PLAT_FORM_LIST'
export const SET_BUSINESS_LIST = 'GET_BUSINESS_LIST'
export const SET_SELECT_POSTER = 'SET_SELECT_POSTER'
//社区
export const GET_COMMUNITY_BOX = 'GET_COMMUNITY_BOX'
export const GET_COMMUNITY_STORE = 'GET_COMMUNITY_STORE'


//报名相关
export const GET_SIGN_INF = 'GET_SIGN_INF'
export const GET_COST_SET = 'GET_COST_SET'
export const GET_SIGN_SET = 'GET_SIGN_SET'

export const SET_ACTIVITY_MY_LIST = 'SET_ACTIVITY_MY_LIST'

export const SET_ACTIVITY_LIST = 'SET_ACTIVITY_LIST'

export const SET_REPLY_VALUE = 'SET_REPLY_VALUE'

export const SET_ACTIVITY_ORDER = 'SET_ACTIVITY_ORDER'
export const SET_ACTIVITY_ARR = 'SET_ACTIVITY_ARR'
export const SET_ADD_BOX_ARR = 'SET_ADD_BOX_ARR'
export const SET_ACTIVITY_DETAIL = 'SET_ACTIVITY_DETAIL'
export const SET_ENROLL_LIST = 'SET_ENROLL_LIST'
export const SET_ACTIVITY_COMMENT_LIST = 'SET_ACTIVITY_COMMENT_LIST'

export const SET_TO_COMMENT = 'SET_TO_COMMENT'
export const SET_ACTIVITY_REWARD_DETAIL_LIST = 'SET_ACTIVITY_REWARD_DETAIL_LIST'
export const SET_ACTIVITY_GOODACT_GOODS = 'SET_ACTIVITY_GOODACT_GOODS'
export const SET_ACTIVITY_ENLIST = 'SET_ACTIVITY_ENLIST'
export const SET_ACTIVITY_TYPE_LIST = 'SET_ACTIVITY_TYPE_LIST'

export const SET_ACTIVITY_HOME_INDEX = 'SET_ACTIVITY_HOME_INDEX'

export const SET_LOGIN_REFRESH = 'SET_LOGIN_REFRESH'

//商品图片
export const GET_GOODS_IMG = 'GET_GOODS_IMG'
//oss图片路径缓存
export const GET_IMG_CACHE = 'GET_IMG_CACHE'
//状态保存
export const GET_STORE_STATE = 'GET_STORE_STATE'
//商品规格
export const GET_GOODS_STANDARD = 'GET_GOODS_STANDARD'




//im状态等...
export const UPDATE_REFRESH_STATE	= 'UPDATE_REFRESH_STATE ' 
export const SET_LOGIN_INFO	= 'SET_LOGIN_INFO' 

export const LOGIN_PORTS_CHANGE	= 'LOGIN_PORTS_CHANGE' 
export const BLACK_LIST	= 'BLACK_LIST' 
export const MARK_IN_BLACK_LIST	= 'MARK_IN_BLACK_LIST' 
export const MUTE_LIST	= 'MUTE_LIST' 
export const SYNC_MARKINMUTE_LIST	= 'SYNC_MARKINMUTE_LIST' 
export const FRIENDS	= 'FRIENDS' 
export const SYNC_FRIENDACTION	= 'SYNC_FRIENDACTION' 
export const MY_INFO	= 'MY_INFO' 
export const USER_INFO	= 'USER_INFO'
export const UPDATE_MY_INFO	= 'UPDATE_MY_INFO' 
export const USERS	= 'USERS' 
export const UPDATE_USER	= 'UPDATE_USER' 
export const TEAMS	= 'TEAMS' 
export const SYNC_CREATE_TEAM	= 'SYNC_CREATE_TEAM' 
export const TEAM_MEMBERS	= 'TEAM_MEMBERS' 
export const SYNC_TEAM_MENBERS_DONE	= 'SYNC_TEAM_MENBERS_DONE' 
export const UPDATE_TEAM_MEMBER	= 'UPDATE_TEAM_MEMBER' 

export const SESSIONS	= 'SESSIONS' 
export const UPDATE_SESSION	= 'UPDATE_SESSION' 
export const ROAMING_MSGS	= 'ROAMING_MSGS' 
export const OFF_LINE_MSGS	= 'OFF_LINE_MSGS' 
export const MSG	= 'MSG' 
export const SYS_MSG	= 'SYS_MSG' 

export const OFF_LINE_SYS_MSGS	= 'OFF_LINE_SYS_MSGS' 
export const UPDATE_SYS_MSG	= 'UPDATE_SYS_MSG' 

export const SYS_MSG_UNREAD	= 'SYS_MSG_UNREAD' 
export const UPDATE_SYS_MSG_UNREAD	= 'UPDATE_SYS_MSG_UNREAD' 
export const OFF_LINE_CUSTOM_SYS_MSGS	= 'OFF_LINE_CUSTOM_SYS_MSGS' 
export const CUSTOM_SYS_MSG	= 'CUSTOM_SYS_MSG' 
export const SYNC_DONE	= 'SYNC_DONE' 

export const UPDATE_SEARCH_LIST	= 'UPDATE_SEARCH_LIST' 
export const UPDATE_USER_INFO	= 'UPDATE_USER_INFO' 

export const UPDATE_DATE_SESSIONS	= 'UPDATE_DATE_SESSIONS' 
export const UPDATE_CURR_SESSIONID	= 'UPDATE_CURR_SESSIONID' 
export const UPDATE_CURR_SESSION_MSGS	= 'UPDATE_CURR_SESSION_MSGS' 
export const UPDATE_CURR_SESSION_ID	= 'UPDATE_CURR_SESSION_ID'
export const UPDATE_MSGS	= 'UPDATE_MSGS'
export const UPDATE_MSGBYID_CLIENT	= 'UPDATE_MSGBYID_CLIENT'
export const PUT_MSG	= 'PUT_MSG'
export const UPDATE_FRIENDS	= 'UPDATE_FRIENDS'

export const SET_DEFAULT_TIMER = 'SET_DEFAULT_TIMER'
export const SET_DEFAULT_TIMER_KEY = 'SET_DEFAULT_TIMER_KEY'

export const IS_MAX_PAGE	= 'IS_MAX_PAGE'
export const IS_SLIDES_TOP	= 'IS_SLIDES_TOP'
export const IS_SLIDES_BOTTOM	= 'IS_SLIDES_BOTTOM'

export const SET_NO_MORE_HISTORY_MSGS	= 'SET_NO_MORE_HISTORY_MSGS'
